-- QC-BKP modernized PostgreSQL schema
-- Based on QC-BKP_Modernization_Blueprint.pdf

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('super_admin', 'doctor', 'user', 'auditor');
    END IF;

    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role')
       AND NOT EXISTS (
           SELECT 1
           FROM pg_enum e
           JOIN pg_type t ON t.oid = e.enumtypid
           WHERE t.typname = 'user_role' AND e.enumlabel = 'auditor'
       ) THEN
        ALTER TYPE user_role ADD VALUE 'auditor';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'claim_status') THEN
        CREATE TYPE claim_status AS ENUM (
            'ready_for_assignment',
            'waiting_for_documents',
            'in_review',
            'needs_qc',
            'completed',
            'withdrawn'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'parse_status') THEN
        CREATE TYPE parse_status AS ENUM ('pending', 'processing', 'succeeded', 'failed');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'decision_recommendation') THEN
        CREATE TYPE decision_recommendation AS ENUM (
            'approve',
            'reject',
            'manual_review',
            'need_more_evidence'
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_user_id BIGINT UNIQUE,
    username VARCHAR(60) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_bank_details (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    account_holder_name VARCHAR(255) NOT NULL DEFAULT '',
    bank_name VARCHAR(255) NOT NULL DEFAULT '',
    branch_name VARCHAR(255) NOT NULL DEFAULT '',
    account_number VARCHAR(64) NOT NULL DEFAULT '',
    payment_rate VARCHAR(64) NOT NULL DEFAULT '',
    ifsc_code VARCHAR(32) NOT NULL DEFAULT '',
    upi_id VARCHAR(255) NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(100) NOT NULL DEFAULT '',
    updated_by VARCHAR(100) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth_logs (
    id BIGSERIAL PRIMARY KEY,
    legacy_auth_log_id BIGINT,
    user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    username VARCHAR(60) NOT NULL,
    role user_role NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    user_agent VARCHAR(255) NOT NULL,
    success BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    role_snapshot user_role NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    external_claim_id VARCHAR(100) NOT NULL UNIQUE,
    patient_name VARCHAR(255),
    patient_identifier VARCHAR(100),
    status claim_status NOT NULL DEFAULT 'waiting_for_documents',
    assigned_doctor_id VARCHAR(100),
    priority SMALLINT NOT NULL DEFAULT 3,
    source_channel VARCHAR(100),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS claim_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_document_id BIGINT,
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    storage_key TEXT NOT NULL,
    file_name TEXT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT,
    checksum_sha256 CHAR(64),
    parse_status parse_status NOT NULL DEFAULT 'pending',
    page_count INT,
    retention_class VARCHAR(50) NOT NULL DEFAULT 'standard',
    uploaded_by VARCHAR(100),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    parsed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS document_extractions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES claim_documents(id) ON DELETE CASCADE,
    extraction_version VARCHAR(50) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    extracted_entities JSONB NOT NULL,
    evidence_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence NUMERIC(5,4),
    created_by VARCHAR(100) NOT NULL DEFAULT 'system',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (document_id, extraction_version)
);

CREATE TABLE IF NOT EXISTS decision_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_analysis_id BIGINT,
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    extraction_id UUID REFERENCES document_extractions(id) ON DELETE SET NULL,
    rule_version VARCHAR(50) NOT NULL,
    model_version VARCHAR(50),
    fraud_risk_score NUMERIC(5,4),
    qc_risk_score NUMERIC(5,4),
    consistency_checks JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_hits JSONB NOT NULL DEFAULT '[]'::jsonb,
    explanation_summary TEXT,
    recommendation decision_recommendation NOT NULL,
    route_target VARCHAR(100) NOT NULL,
    manual_review_required BOOLEAN NOT NULL DEFAULT TRUE,
    review_priority SMALLINT NOT NULL DEFAULT 3,
    decision_payload JSONB NOT NULL,
    generated_by VARCHAR(100) NOT NULL DEFAULT 'system',
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS report_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    decision_id UUID REFERENCES decision_results(id) ON DELETE SET NULL,
    version_no INT NOT NULL,
    report_status VARCHAR(30) NOT NULL DEFAULT 'draft',
    report_markdown TEXT,
    export_uri TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (claim_id, version_no)
);

CREATE TABLE IF NOT EXISTS claim_report_uploads (
    id BIGSERIAL PRIMARY KEY,
    claim_id UUID NOT NULL UNIQUE REFERENCES claims(id) ON DELETE CASCADE,
    report_export_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    tagging VARCHAR(120),
    subtagging VARCHAR(120),
    opinion TEXT,
    qc_status VARCHAR(10) NOT NULL DEFAULT 'no',
    auditor_rating SMALLINT,
    auditor_rating_by VARCHAR(100),
    auditor_rating_at TIMESTAMPTZ,
    updated_by VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS claim_legacy_data (
    id BIGSERIAL PRIMARY KEY,
    claim_id UUID NOT NULL UNIQUE REFERENCES claims(id) ON DELETE CASCADE,
    legacy_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workflow_events (
    id BIGSERIAL PRIMARY KEY,
    legacy_job_id BIGINT,
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    actor_type VARCHAR(30) NOT NULL,
    actor_id VARCHAR(100),
    event_type VARCHAR(100) NOT NULL,
    event_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feedback_labels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
    decision_id UUID REFERENCES decision_results(id) ON DELETE SET NULL,
    label_type VARCHAR(100) NOT NULL,
    label_value VARCHAR(100) NOT NULL,
    override_reason TEXT,
    notes TEXT,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS model_registry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_key VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    artifact_uri TEXT,
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (model_key, version)
);

CREATE TABLE IF NOT EXISTS rule_registry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_key VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    rule_definition JSONB NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (rule_key, version)
);

CREATE TABLE IF NOT EXISTS openai_claim_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    scope_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    decision VARCHAR(20) NOT NULL DEFAULT 'QUERY',
    severity VARCHAR(30) NOT NULL DEFAULT 'SOFT_QUERY',
    priority INT NOT NULL DEFAULT 999,
    required_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS openai_diagnosis_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criteria_id VARCHAR(20) NOT NULL UNIQUE,
    diagnosis_name VARCHAR(255) NOT NULL,
    aliases_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    decision VARCHAR(20) NOT NULL DEFAULT 'QUERY',
    severity VARCHAR(30) NOT NULL DEFAULT 'SOFT_QUERY',
    priority INT NOT NULL DEFAULT 999,
    required_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS openai_claim_rule_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_analysis_id BIGINT,
    claim_id VARCHAR(100) NOT NULL,
    suggestion_type VARCHAR(20) NOT NULL DEFAULT 'new_rule',
    target_rule_id VARCHAR(32),
    proposed_rule_id VARCHAR(32),
    suggested_name VARCHAR(255) NOT NULL,
    suggested_decision VARCHAR(20) NOT NULL DEFAULT 'QUERY',
    suggested_conditions TEXT NOT NULL,
    suggested_remark_template TEXT,
    suggested_required_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_context_text TEXT,
    generator_confidence SMALLINT NOT NULL DEFAULT 0,
    generator_reasoning TEXT,
    generator_response_json JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reviewed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    approved_rule_id VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (source_analysis_id)
);

CREATE TABLE IF NOT EXISTS medicine_component_lookup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_key VARCHAR(160) NOT NULL UNIQUE,
    medicine_name VARCHAR(200) NOT NULL,
    components TEXT NOT NULL,
    subclassification VARCHAR(80) NOT NULL DEFAULT '',
    is_high_end_antibiotic BOOLEAN NOT NULL DEFAULT FALSE,
    source VARCHAR(40) NOT NULL DEFAULT 'table',
    last_checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE openai_claim_rules
    ADD COLUMN IF NOT EXISTS conditions TEXT,
    ADD COLUMN IF NOT EXISTS remark_template TEXT,
    ADD COLUMN IF NOT EXISTS version VARCHAR(20) NOT NULL DEFAULT '1.0',
    ADD COLUMN IF NOT EXISTS source VARCHAR(40) NOT NULL DEFAULT 'manual';

ALTER TABLE openai_diagnosis_criteria
    ADD COLUMN IF NOT EXISTS diagnosis_key VARCHAR(160),
    ADD COLUMN IF NOT EXISTS remark_template TEXT,
    ADD COLUMN IF NOT EXISTS version VARCHAR(20) NOT NULL DEFAULT '1.0',
    ADD COLUMN IF NOT EXISTS source VARCHAR(40) NOT NULL DEFAULT 'manual';

CREATE UNIQUE INDEX IF NOT EXISTS uq_openai_diagnosis_criteria_diagnosis_key ON openai_diagnosis_criteria(diagnosis_key);
CREATE INDEX IF NOT EXISTS idx_openai_claim_rule_suggestions_status ON openai_claim_rule_suggestions(status);
CREATE INDEX IF NOT EXISTS idx_openai_claim_rule_suggestions_claim_id ON openai_claim_rule_suggestions(claim_id);
CREATE INDEX IF NOT EXISTS idx_medicine_component_lookup_name ON medicine_component_lookup(medicine_name);
CREATE INDEX IF NOT EXISTS idx_medicine_component_lookup_subclassification ON medicine_component_lookup(subclassification);
CREATE INDEX IF NOT EXISTS idx_medicine_component_lookup_high_end ON medicine_component_lookup(is_high_end_antibiotic);
ALTER TABLE auth_logs
    ADD COLUMN IF NOT EXISTS legacy_auth_log_id BIGINT;
ALTER TABLE claim_documents
    ADD COLUMN IF NOT EXISTS legacy_document_id BIGINT;
ALTER TABLE decision_results
    ADD COLUMN IF NOT EXISTS legacy_analysis_id BIGINT;
ALTER TABLE workflow_events
    ADD COLUMN IF NOT EXISTS legacy_job_id BIGINT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_logs_legacy_auth_log_id ON auth_logs(legacy_auth_log_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_claim_documents_legacy_document_id ON claim_documents(legacy_document_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_claim_documents_claim_storage_key ON claim_documents(claim_id, storage_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_decision_results_legacy_analysis_id ON decision_results(legacy_analysis_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_workflow_events_legacy_job_id ON workflow_events(legacy_job_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_auth_logs_user_id ON auth_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_logs_created_at ON auth_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_claims_status_created_at ON claims(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_claim_documents_claim_id ON claim_documents(claim_id);
CREATE INDEX IF NOT EXISTS idx_document_extractions_claim_id ON document_extractions(claim_id);
CREATE INDEX IF NOT EXISTS idx_decision_results_claim_generated_at ON decision_results(claim_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_versions_claim_id ON report_versions(claim_id);
CREATE INDEX IF NOT EXISTS idx_claim_report_uploads_claim_id ON claim_report_uploads(claim_id);
CREATE INDEX IF NOT EXISTS idx_claim_legacy_data_claim_id ON claim_legacy_data(claim_id);
CREATE INDEX IF NOT EXISTS idx_workflow_events_claim_occurred_at ON workflow_events(claim_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_labels_claim_id ON feedback_labels(claim_id);
CREATE INDEX IF NOT EXISTS idx_openai_claim_rules_active_priority ON openai_claim_rules(is_active, priority);
CREATE INDEX IF NOT EXISTS idx_openai_diagnosis_criteria_active_priority ON openai_diagnosis_criteria(is_active, priority);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_claims_updated_at ON claims;
CREATE TRIGGER trg_claims_updated_at
BEFORE UPDATE ON claims
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_openai_claim_rules_updated_at ON openai_claim_rules;
CREATE TRIGGER trg_openai_claim_rules_updated_at
BEFORE UPDATE ON openai_claim_rules
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_openai_diagnosis_criteria_updated_at ON openai_diagnosis_criteria;
CREATE TRIGGER trg_openai_diagnosis_criteria_updated_at
BEFORE UPDATE ON openai_diagnosis_criteria
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_openai_claim_rule_suggestions_updated_at ON openai_claim_rule_suggestions;
CREATE TRIGGER trg_openai_claim_rule_suggestions_updated_at
BEFORE UPDATE ON openai_claim_rule_suggestions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_medicine_component_lookup_updated_at ON medicine_component_lookup;
CREATE TRIGGER trg_medicine_component_lookup_updated_at
BEFORE UPDATE ON medicine_component_lookup
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_user_bank_details_user_id ON user_bank_details(user_id);

